// My header
// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type DownloadEvent = { event: "Started"; data: { contentLength: string | null } } | { event: "Progress"; data: { chunkLength: string } } | { event: "Finished" }

export type UpdateMetadata = { version: string; currentVersion: string }

const ARGS_MAP = { '':'{"fetch_update":[],"install_update":["on_event"]}' }
export type Router = { '': { fetch_update: () => Promise<UpdateMetadata | null>, 
install_update: (onEvent: TAURI_CHANNEL<DownloadEvent>) => Promise<null> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
