name: covector version or publish

on:
  workflow_call:
    outputs:
      release-id:
        description: The ID of the created release.
        value: ${{ jobs.version-or-publish.outputs.release-id }}
      app-version:
        value: ${{ jobs.version-or-publish.outputs.app-version }}
        description: "The version of the application."

      matrix:
        description: "Matrix for publish jobs"
        value: ${{ jobs.version-or-publish.outputs.matrix }}

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: "sccache"
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  version-or-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 65
    outputs:
      release-id: ${{ steps.covector.outputs.releaseId }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      app-version: ${{ steps.get-version.outputs.version }}

    steps:
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies (ubuntu only)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev build-essential librsvg2-dev patchelf webkit2gtk-driver zstd xvfb curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev # libappindicator3-dev
          version: 1.0

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - run: pnpm i --frozen-lockfile

      - id: install-rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: swatinem/rust-cache@v2

        with:
          key: ${{ steps.install-rust.outputs.cachekey }}
          cache-all-crates: true
          cache-on-failure: true
          workspaces: |
            src-tauri

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_GITHUB_CI_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_CI_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: covector version or publish (publish when no change files present)
        uses: jbolda/covector/packages/action@covector-v0.12
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: "version-or-publish"
          createRelease: true
          draftRelease: true
          recognizeContributors: true

      - run: pnpm i --lockfile-only
      - run: cargo fetch
        working-directory: src-tauri

      - name: Create Pull Request With Versions Bumped
        id: cpr
        uses: peter-evans/create-pull-request@v7
        if: steps.covector.outputs.commandRan == 'version'
        with:
          title: "Publish New Versions"
          commit-message: "publish new versions"
          sign-commits: true
          labels: "version updates"
          branch: "release"
          body: ${{ steps.covector.outputs.change }}

      - uses: actions/checkout@v4
        if: steps.covector.outputs.commandRan == 'version'
        with:
          ref: "release"

      - run: pnpm i
      - run: pnpm build:scripts

      - id: get-version
        run: |
          VERSION=$(node .dist/print-version.mjs)
          echo "version=$(echo $VERSION | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - id: get-msi-version
        run: |
          MSI_VERSION=$(node .dist/print-msi-version.mjs)
          echo "msi-version=$MSI_VERSION" >> $GITHUB_OUTPUT

      - id: get-release-channel
        run: |
          RELEASE_CHANNEL=$(node .dist/print-release-channel.mjs)
          echo "release-channel=$RELEASE_CHANNEL" >> $GITHUB_OUTPUT

      - id: set-matrix
        run: |
          if [ "$RELEASE_CHANNEL" = "stable" ]; then
            matrixFile="./.github/fixtures/matrix_publish_stable.json"
          else
            matrixFile="./.github/fixtures/matrix_publish.json"
          fi
            matrix=$(jq '.' $matrixFile)
            echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
        env:
          RELEASE_CHANNEL: ${{ steps.get-release-channel.outputs.release-channel }}
      - name: Print matrix
        run: |
          echo "matrix=$matrix"
        env:
          matrix: ${{ steps.set-matrix.outputs.matrix }}

      - name: "v${{ steps.get-version.outputs.version }}"
        env:
          CURRENT_VERSION: ${{ steps.get-version.outputs.version }}
          MSI_VERSION: ${{ steps.get-msi-version.outputs.msi-version }}
        run: |
          printf "\n\n\n      ✈️      ✈️      ✈️      \n\n"
          printf "\033[1mVersion : \033[32m${CURRENT_VERSION}\033[0m\n"
          printf "\033[1mMSI Version : \033[33m${MSI_VERSION}\033[0m\n"
          printf "\n      ✈️      ✈️      ✈️      \n\n\n\n "
