name: main workflow

on:
  push:
    branches:
      - main

jobs:
  version-or-publish:
    uses: ./.github/workflows/covector-version-or-publish.yml
    secrets: inherit

  publish-to-auto-release:
    needs: version-or-publish
    if: needs.version-or-publish.outputs.release-id
    uses: ./.github/workflows/publish-app.yml
    secrets: inherit
    with:
      release-id: ${{ needs.version-or-publish.outputs.release-id }}
      matrix: ${{ needs.version-or-publish.outputs.matrix }}

  push-to-s3:
    name: push ${{ matrix.package }}-v${{ matrix.version }} to S3
    needs: [version-or-publish, publish-to-auto-release]
    if: needs.version-or-publish.outputs.command-ran == 'publish'
    uses: ./.github/workflows/push-to-s3.yml
    secrets: inherit
    with:
      bucket-name: my-tauri-updater
      package-name: ${{ matrix.package }}
      release-id: ${{ needs.version-or-publish.outputs.release-id }}
      version: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.version-or-publish.outputs.packages-published) }}
