name: main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version-or-publish:
    uses: ./.github/workflows/covector-version-or-publish.yml
    secrets: inherit

  publish-to-auto-release:
    needs: version-or-publish
    if: needs.version-or-publish.outputs.release-id
    uses: ./.github/workflows/publish-to-auto-release.yml
    secrets: inherit
    with:
      release-id: ${{ needs.version-or-publish.outputs.release-id }}
      matrix: ${{ needs.version-or-publish.outputs.matrix }}

  push-to-s3:
    needs: [version-or-publish, publish-to-auto-release]
    uses: ./.github/workflows/push-to-s3.yml
    secrets: inherit

    with:
      release-id: ${{ needs.version-or-publish.outputs.release-id }}
      app-version: ${{ needs.version-or-publish.outputs.app-version }}
      package-name: "app"
      bucket-name: "my-tauri-updater"
