name: main workflow

on:
  push:
    branches:
      - main

jobs:
  version-or-publish:
    uses: ./.github/workflows/covector-version-or-publish.yml
    secrets: inherit

  build-to-release:
    needs: version-or-publish
    if: needs.version-or-publish.outputs.command-ran == 'publish'
    uses: ./.github/workflows/build-to-release.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.version-or-publish.outputs.build-matrix) }}
    with:
      package: ${{ matrix.package }}
      release-id: ${{ needs.version-or-publish.outputs.release-id }}
      platform: ${{ matrix.platform }}
      args: ${{ matrix.args }}
      include-debug: ${{ matrix.includeDebug }}
      include-release: ${{ matrix.includeRelease }}

  # push-to-s3:
  #   needs: [version-or-publish, build-to-release]
  #   if: needs.version-or-publish.outputs.command-ran == 'publish'
  #   uses: ./.github/workflows/push-to-s3.yml
  #   name: push ${{ matrix.package }}-v${{ matrix.version }} to S3
  #   secrets: inherit
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ fromJson(needs.version-or-publish.outputs.packages-published) }}
  #   with:
  #     bucket-name: my-tauri-updater
  #     package-name: ${{ matrix.package }}
  #     release-id: ${{ needs.version-or-publish.outputs.release-id }}
  #     version: ${{ matrix.version }}
