name: matrix-prep
on:
  workflow_call:
    inputs:
      releaseChannel:
        default: "stable"
        type: string
      releaseId:
        required: true
        type: string
    outputs:
      matrix:
        description: "Matrix for publish jobs"
        value: ${{ jobs.matrix_prep.outputs.matrix }}

jobs:
  matrix_prep:
    runs-on: "ubuntu-latest"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          if [ "$RELEASE_CHANNEL" = "stable" ]; then
            matrixFile="./.github/fixtures/matrix_publish_stable.json"
          else
            matrixFile="./.github/fixtures/matrix_publish.json"
          fi
          matrix=$(jq '.' $matrixFile)
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
        env:
          RELEASE_CHANNEL: ${{ inputs.releaseChannel }}
      - name: Print matrix
        run: |
          echo "matrix=$matrix"
        env:
          matrix: ${{ steps.set-matrix.outputs.matrix }}
